---
apiVersion: tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: webhook
spec:
  serviceAccountName: pipeline
  triggers:
    - name: petclinic-webhook-commit
      # interceptors:
      #   - github:
      #       eventTypes:
      #         - push
      binding:
        name: github-triggerbinding
      template:
        name: postit-backend-deploy
    # - name: petclinic-webhook-pr
    #   interceptors:
    #     - github:
    #         eventTypes:
    #           - pull_request
    #   binding:
    #     name: github-pr-triggerbinding
    #   template:
    #     name: petclinic-trigger-template
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: webhook
  labels:
    app.kubernetes.io/managed-by: EventListener
    app.kubernetes.io/part-of: Triggers
    eventlistener: webhook
spec:
  port:
    targetPort: 8080
  to:
    kind: "Service"
    name: el-webhook
    weight: 100
