---
apiVersion: tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: postit-backend-deploy-pr
spec:
  params:
  - name: gitrevision
    description: The git revision
    default: master
  - name: gitrepositoryurl
    description: The git repository url
  - name: message
    description: The message to print
    default: This is the default message
  - name: contenttype
    description: The Content-Type of the event
  resourcetemplates:
  - apiVersion: tekton.dev/v1alpha1
    kind: PipelineRun
    metadata:
      generateName: postit-backend-deploy-pr-run-
      labels:
        tekton.dev/pipeline: postit-backend-deploy-pr
    spec:
      pipelineRef:
        name: postit-backend-deploy-pr
      params:
      - name: COMMIT_ID
        value: $(params.gitrevision)
      resources:
      - name: app-git
        resourceSpec:
          type: git
          params:
            - name: revision
              value: $(params.gitrevision)
            - name: url
              value: $(params.gitrepositoryurl)
      - name: app-image
        resourceSpec:
          type: image
          params:
          - name: url
            value: image-registry.openshift-image-registry.svc:5000/post-app-sun/quarkus-backend:$(params.gitrevision)
      workspaces:
      - name: local-maven-repo
        persistentVolumeClaim:
          claimName: maven-repo-pvc