---
apiVersion: tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: posit-backend-deploy-template
spec:
  params:
  - name: gitrevision
    description: The git revision
    default: master
  - name: gitrepositoryurl
    description: The git repository url
  - name: message
    description: The message to print
    default: This is the default message
  - name: contenttype
    description: The Content-Type of the event
  resourcetemplates:
  - apiVersion: tekton.dev/v1alpha1
    kind: PipelineRun
    metadata:
      generateName: posit-backend-deploy-run-
      labels:
        tekton.dev/pipeline: posit-backend-deploy
    spec:
      pipelineRef:
        name: posit-backend-deploy
      resources:
      - name: app-git
        resourceRef:
          name: postit-git
      - name: app-image
        resourceRef:
          name: postit-backend-image
      workspaces:
      - name: local-maven-repo
        persistentVolumeClaim:
          claimName: maven-repo-pvc