apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  generateName: postit-backend-deploy-run-
spec:
  pipelineRef:
    name: postit-backend-deploy
  resources:
  - name: app-git
    resourceRef:
      name: postit-git
  - name: app-image
    resourceRef:
      name: postit-backend-image
  workspaces:
  - name: local-maven-repo
    persistentVolumeClaim:
      claimName: maven-repo-pvc